name: Lemon
main: main.Main
version: 1.0.0
api-version: 1.18
softdepend: [ Vault ]
commands:
  파티:
    description: 파티 명령어
  친구:
    description: 친구 명령어
  돈:
    description: 돈 명령어
  귓속말:
    description: 귓속말 명령어
    aliases: [ 귓, 귓말, w, msg, tell ]
  설정:
    description: 설정 명령어
    aliases: [ settings ]
  나침반:
    description: 나침반 명령어
    aliases: [ compass ]
  레시피:
    description: 레시피 명령어
    aliases: [ recipe ]
  오류:
    description: 오류(예외) 관리 명령어
    aliases: [ error, exception ]
  tpa:
    description: 플레이어 텔레포트 요청 명령어
  tpaccept:
    description: 플레이어 텔레포트 수락 명령어
  tpdeny:
    description: 플레이어 텔레포트 거절 명령어
